### ISSUE TITLE
allow failure option

### ISSUE THREAD

**Issue by aminya** [nick-invision/retry#11]
I have a command that I know it fails on a specific operating system, but I want to run it as a reminder to fix the issue. However, I don't want the step to fail the whole job. Is there a way to do that using `retry`?

**Comment by aminya** [comment]
@nick-invision Can we add the example to the documentation? This is a very useful feature!

**Comment by czifro** [comment]
I think there's a valid case now to support this in action. With the rollout of improved composite actions: https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/ , there is no way to specify `continue-on-error`. Furthermore, composite actions don't support `if: failure()`, so it is not possible to have failure tracks in composite actions.
