### ISSUE TITLE
v2 swallows command output?

### ISSUE THREAD

**Issue by iNikem** [nick-invision/retry#21]
After upgrading to v2 of this action we don't see any output from the command ran by this action:

<img width="743" alt="Screenshot 2020-10-26 at 09 39 40" src="https://user-images.githubusercontent.com/3010154/97145739-5cc2a180-176f-11eb-9d23-90c41a846579.png">

**Comment by nick-invision** [comment]
Thanks for the issue @iNikem, can you configure a secret named `ACTIONS_STEP_DEBUG` in your repo (repo->settings->secrets) then include the action output for the retry step?

**Comment by zhongnansu** [comment]
@nick-invision Hi, I am having the same issue, could you explain what do yo mean by "include the action output for the retry step" ? What value I should set for the secret? According to [this](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging),  I set true for `ACTIONS_STEP_DEBUG`, but it doesn't work for the retry step.

**Comment by nick-invision** [comment]
Once you add the secret named `ACTIONS_STEP_DEBUG` and set the value to `true` it should output more detailed logs when you run your workflow.  If you want to send me the raw output displayed that would help debug this further.

@zhongnansu What command are you attempting to run that has no output?

**Comment by kadosh1000** [comment]
@nick-invision same issue for me after upgrading to v2.0.0 from v1.0.0
It seems that neither stdout nor stderr are being printed.
The command I am running is a basic npm command.

setting `ACTIONS_STEP_DEBUG` to `true`, this is the output I get:

> ##[debug]Evaluating condition for step: 'Sync'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Sync
##[debug]Loading inputs
##[debug]Loading env
Run nick-invision/retry@v2.0.0
  with:
    timeout_minutes: 20
    max_attempts: 3
    command: npm run sync
    retry_wait_seconds: 2
    polling_interval_seconds: 1
::set-output name=total_attempts::1
##[debug]='1'
##[debug]Code: 1
##[debug]Signal: null
##[debug]Waited 2002ms
##[debug]Configured wait: 2000ms
Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
::set-output name=total_attempts::2
##[debug]='2'
##[debug]Code: 0
##[debug]Signal: null
Command completed after 2 attempt(s).
::set-output name=exit_code::0
##[debug]='0'
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Sync

I have to revert back to v1.0.0 until this will be solved.

**Comment by nick-invision** [comment]
Thanks for the debug output! I found the cause and working on the fix. Shouldn't be too much longer.

**Comment by nick-invision** [comment]
@iNikem @zhongnansu @kadosh1000 This has been fixed and published as both `uses: nick-invision/retry@v2.0.1` and ` uses: nick-invision/retry@v2`.  Thanks for reporting!
