### ISSUE TITLE
Why does timeout_seconds have to be as long as retry_wait_seconds ?

### ISSUE THREAD

**Issue by tetchel** [nick-invision/retry#24]
Firstly, thanks for the useful action. I hope it helps motivate GitHub to add this as built-in functionality soon enough.

For my use-case, I wanted to ping an http endpoint with curl, but it was failing because the app I was pinging was not up yet.

So I wanted to add this action to retry if the ping failed so that it would succeed once the app came up.

Initially I set it up to timeout after 2s (since the request should be fast) and try again after 10s
It failed because `timeout_seconds 2s less than retry_wait_seconds 10s`

but, I think this should be allowed.

**Comment by nick-invision** [comment]
I'm not sure what my motivation was for preventing timeout_seconds < retry_wait_seconds, but I fixed it so this is now allowed 😄 .  Thanks for the report

This is available in `nick-invision/retry@v2.2.0` or `nick-invision/retry@v2`
