### ISSUE TITLE
Option to suppress warning output on retry

### ISSUE THREAD

**Issue by tetchel** [nick-invision/retry#25]
If it's "normal" for my workflow step to have to run multiple times, I don't like having the warning output on my workflow. 

I would prefer if I could configure this action so I could lower that output to info level.

**Comment by nick-invision** [comment]
I've added the input `warning_on_retry` which defaults to `true` however you can set it to `false` and it will just log (not warn) on retry.  Thanks for the input.

This is available in `nick-invision/retry@v2.2.0` or `nick-invision/retry@v2`
