### ISSUE TITLE
Unclear what the error message is upon failure

### ISSUE THREAD

**Issue by jvanzyl** [nick-invision/retry#4]
We are trying out the retry action and we have some output like this:

```
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node',
  path: 'node',
  spawnargs: [
    '/home/concord/actions-runner/_work/_actions/nick-invision/retry/v1.0.0/dist/exec.js',
    './mvnw test -B -Dair.check.skip-all -pl plugin/starburst-snowflake -Pjdbc-integration-tests ${SNOWFLAKE_CONFIG}'
  ]
}
```

Does this mean the command we are trying to run is not present?

**Comment by nick-invision** [comment]
@jvanzyl Could you include your workflow file to help understand how you are using this?

**Comment by nick-invision** [comment]
@jvanzyl Could you include your workflow file to help understand how you are using this?

Also, does running just this snippet work in your workflow? I'm curious what ./mvnw is and whether it's executable.

name: Run without retry for debugging
run: "./mvnw test -B -Dair.check.skip-all -pl plugin/starburst-snowflake -Pjdbc-integration-tests ${SNOWFLAKE_CONFIG}"
If it doesn't run with that plain run command, then this retry action also will not work. The action simply wraps your command in a call to execSync and retries on failure.

Either way, provide me the workflow.yml, what ./mvnw is (and if it's executable), and whether the above run command works for you. Then I can attempt to reproduce and find a way to better capture and surface the error that is being improperly handled.

**Comment by jvanzyl** [comment]
That command does work with the `run` command. Let me redact a few things, make sure the flow works and I'll post it here.

**Comment by nick-invision** [comment]
@jvanzyl This was found to be an issue with nodejs not being installed on the self-hosted runner.  If you want to use this, you would need to either install nodejs on the self-hosted runner, or run this action prior to the command.

```
- name: Setup Node.js environment
   uses: actions/setup-node@v2.1.2
```
